---
- name: Install Duply
  apt: pkg={{ item }} state=present
  with_items:
    - python-boto
    - duply={{ duply_version }}

- name: Create Duply configuration directory structure
  file: path=/etc/duply/{{ duply_profile }}
        mode=0700
        state=directory

- name: Configure Duply
  template: src={{ item }}.j2
            dest=/etc/duply/{{ duply_profile }}/{{ item }}
            mode=0600
  with_items:
    - conf
    - exclude

- name: Setup incremental cronjob for Duply
  template: src=duply.incr.j2
            dest=/etc/cron.daily/duply.incr
            mode="0755"

- name: Setup full cronjob for Duply
  template: src=duply.full.j2
            dest=/etc/cron.weekly/duply.full
            mode="0755"
